# docker-compose up amqWithScheduler rmqwithscheduler
amqWithScheduler:
  image: viliusl/ubuntu-activemq-server
  volumes:
    - ./dockerFiles/activemqWithScheduler.xml:/opt/apache-activemq-5.9.0/conf/activemq.xml:ro
  mem_limit: 512m
  ports:
    - "61616:61616"
    - "8161:8161"
rmqwithscheduler:
  build: rabbitmqwithscheduler/.
  environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=admin
  ports:
    - "15672:15672"
    - "5672:5672"
    - "4369:4369"
    - "25672:25672"

# docker-compose up amqWithComposite
amqWithComposite:
  image: viliusl/ubuntu-activemq-server
  volumes:
    - ./dockerFiles/activemqWithComposite.xml:/opt/apache-activemq-5.9.0/conf/activemq.xml:ro
  mem_limit: 512m
  ports:
    - "61616:61616"
    - "8161:8161"

# docker-compose up tomee
tomee:
  image: tomee:8-jre-7.0.0-M1-plus
  volumes:
      - ./dockerFiles/tomee-users.xml:/usr/local/tomee/conf/tomcat-users.xml:ro
      - ./dockerFiles/tomee.xml:/usr/local/tomee/conf/tomee.xml:ro
  mem_limit: 512m
  ports:
    - "8080:8080"
  links:
    - justAmq

# docker-compose up justAmq
justAmq:
  image: viliusl/ubuntu-activemq-server
  mem_limit: 512m
  ports:
    - "61616:61616"
    - "8161:8161"

# docker-compose up amqWithDb1
# docker-compose up amqWithDb2
postgres:
  image: postgres:9.5
  environment:
    - POSTGRES_PASSWORD=1234
amqWithDb1:
  image: viliusl/ubuntu-activemq-server
  dns: 8.8.8.8
  links:
    - postgres
  volumes:
    - ./dockerFiles/activemqWithDb.xml:/opt/apache-activemq-5.9.0/conf/activemq.xml:ro
    - ./dockerFiles/postgresql-9.4-1202.jdbc4.jar:/opt/apache-activemq-5.9.0/lib/postgresql-9.4-1202.jdbc4.jar:ro
  ports:
    - "8161:8161"
    - "61616:61616"
amqWithDb2:
  image: viliusl/ubuntu-activemq-server
  dns: 8.8.8.8
  links:
    - postgres
  volumes:
    - ./dockerFiles/activemqWithDb.xml:/opt/apache-activemq-5.9.0/conf/activemq.xml:ro
    - ./dockerFiles/postgresql-9.4-1202.jdbc4.jar:/opt/apache-activemq-5.9.0/lib/postgresql-9.4-1202.jdbc4.jar:ro
  ports:
    - "8162:8161"
    - "61617:61616"

# docker-compose up amqNetwork1 amqNetwork2
amqNetwork1:
  image: viliusl/ubuntu-activemq-server
  volumes:
    - ./dockerFiles/activemqWithNetwork1.xml:/opt/apache-activemq-5.9.0/conf/activemq.xml:ro
  mem_limit: 512m
  links:
    - dnsdock
  hostname: amq1
  dns: 172.17.0.1
  environment:
    - DNSDOCK_NAME=amq1
    - DNSDOCK_IMAGE=amq1
  ports:
    - "61616:61616"
    - "8161:8161"
amqNetwork2:
  image: viliusl/ubuntu-activemq-server
  dns: 172.17.0.1
  volumes:
    - ./dockerFiles/activemqWithNetwork2.xml:/opt/apache-activemq-5.9.0/conf/activemq.xml:ro
  mem_limit: 512m
  links:
    - dnsdock
  hostname: amq2
  environment:
    - DNSDOCK_NAME=amq2
    - DNSDOCK_IMAGE=amq2
  ports:
    - "61617:61616"
    - "8162:8161"
dnsdock:
  image: tonistiigi/dnsdock:v1.10.0
  volumes:
    - /var/run/docker.sock:/run/docker.sock
  ports:
    - 172.17.0.1:53:53/udp

# docker-compose up amqWithRedeliveryAndScheduler
amqWithRedeliveryAndScheduler:
  image: viliusl/ubuntu-activemq-server
  volumes:
    - ./dockerFiles/activemqWithSchedulerAndRedelivery.xml:/opt/apache-activemq-5.9.0/conf/activemq.xml:ro
  mem_limit: 512m
  ports:
    - "61616:61616"
    - "8161:8161"
# docker-compose up amqWithVirtualTopic
amqWithVirtualTopic:
  image: viliusl/ubuntu-activemq-server
  volumes:
    - ./dockerFiles/activemqWithVirtualTopic.xml:/opt/apache-activemq-5.9.0/conf/activemq.xml:ro
  mem_limit: 512m
  ports:
    - "61616:61616"
    - "8161:8161"
